apiVersion: v1
kind: Namespace
metadata:
  name: eazytraining
status:
  phase: Active
---
kind: Service 
apiVersion: v1 
metadata:
  name: eazytraining-nodeport
  namespace: eazytraining
spec:
  type: NodePort
  selector:
    app: eazytraining 
  ports:
    - nodePort: 31000
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eazytraining
  labels:
    app: eazytraining
  namespace: eazytraining
spec:
  replicas: 3
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: eazytraining
  template:
    metadata:
      labels:
        app: eazytraining
    spec:
      containers:
        - image: 192.168.100.10:5000/projet-fil-rouge-groupe1:v1___PLATFORMTAG___
          name: fil-rouge-groupe1
          ports:
          - containerPort: 3000
            name: eazytraining